//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomoU.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Estado
    {
        public tbl_CAT_Estado()
        {
            this.tbl_CAT_Registro = new HashSet<tbl_CAT_Registro>();
        }
    
        public int intEstadoID { get; set; }
        public string vchEstado { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchUserAdmin { get; set; }
    
        public virtual ICollection<tbl_CAT_Registro> tbl_CAT_Registro { get; set; }
    }
}
