//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomoU.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SYS_Configuraciones
    {
        public string vchConfiguracion { get; set; }
        public string vchValor { get; set; }
    }
}
