//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomoU.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_Registro
    {
        public int intRegistroID { get; set; }
        public string vchNombre { get; set; }
        public string vchEmail { get; set; }
        public string vchTelefono { get; set; }
        public string vchHospital { get; set; }
        public string vchEspecialidad { get; set; }
        public string vchEquipoMasto { get; set; }
        public Nullable<bool> bitTomosintesis { get; set; }
        public Nullable<bool> bitBeca { get; set; }
        public string vchFolioBeca { get; set; }
        public string vchPagoFolio { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public string vchUserAdmin { get; set; }
        public Nullable<bool> bitConfirmado { get; set; }
        public Nullable<int> intEstadoID { get; set; }
    
        public virtual tbl_CAT_Estado tbl_CAT_Estado { get; set; }
    }
}
