//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomoU.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TomoUDBEntities : DbContext
    {
        public TomoUDBEntities()
            : base("name=TomoUDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_CAT_Registro> tbl_CAT_Registro { get; set; }
        public DbSet<tbl_SYS_Configuraciones> tbl_SYS_Configuraciones { get; set; }
        public DbSet<tbl_CAT_Estado> tbl_CAT_Estado { get; set; }
    
        public virtual ObjectResult<string> stp_encripta_cadena(string cadena)
        {
            var cadenaParameter = cadena != null ?
                new ObjectParameter("Cadena", cadena) :
                new ObjectParameter("Cadena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("stp_encripta_cadena", cadenaParameter);
        }
    }
}
